// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsYlO2cS5HNBqyv6dVA4_Yykj-ve8N9Sc',
    appId: '1:24060433750:web:3f93d338fa5a0e7687b2f7',
    messagingSenderId: '24060433750',
    projectId: 'student-management-syste-66ac2',
    authDomain: 'student-management-syste-66ac2.firebaseapp.com',
    storageBucket: 'student-management-syste-66ac2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4CRc5XJzw4Z--SNF_MQCKhISswSyUn6Q',
    appId: '1:24060433750:android:a54b952d3845ca2987b2f7',
    messagingSenderId: '24060433750',
    projectId: 'student-management-syste-66ac2',
    storageBucket: 'student-management-syste-66ac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCb7F2qAznUPE5LYtrjSEJwZX6KwsegcQ',
    appId: '1:24060433750:ios:24280754e978c35187b2f7',
    messagingSenderId: '24060433750',
    projectId: 'student-management-syste-66ac2',
    storageBucket: 'student-management-syste-66ac2.firebasestorage.app',
    iosBundleId: 'com.student.app.studentManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCb7F2qAznUPE5LYtrjSEJwZX6KwsegcQ',
    appId: '1:24060433750:ios:24280754e978c35187b2f7',
    messagingSenderId: '24060433750',
    projectId: 'student-management-syste-66ac2',
    storageBucket: 'student-management-syste-66ac2.firebasestorage.app',
    iosBundleId: 'com.student.app.studentManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsYlO2cS5HNBqyv6dVA4_Yykj-ve8N9Sc',
    appId: '1:24060433750:web:dd84e83d7bd85ea087b2f7',
    messagingSenderId: '24060433750',
    projectId: 'student-management-syste-66ac2',
    authDomain: 'student-management-syste-66ac2.firebaseapp.com',
    storageBucket: 'student-management-syste-66ac2.firebasestorage.app',
  );
}
